# Generated by Django 3.2 on 2021-06-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poems', '0002_auto_20210606_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
